const level1 = new Level([
    // new Chicken(),
    // new Chicken(),
    // new Chicken(),
    // new Chicken(),
    // new Chicken(),
    // new smallChicken(),
    // new smallChicken(),
    // new smallChicken(),  
],
[
    new Endboss() 
], 
[
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud()
],
backgroundObjects = [
    new BackgroundObject('img/5_background/layers/air.png', 0 , -719),
    new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 180 , -719),
    new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 180 , -719),
    new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 180 , -719),

    new BackgroundObject('img/5_background/layers/air.png', 0 , 0),
    new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 180 , 0),
    new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 180 , 0),
    new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 180 , 0),

    new BackgroundObject('img/5_background/layers/air.png', 0 , 719),
    new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 180 , 719),
    new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 180 , 719),
    new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 180 , 719),
    
    new BackgroundObject('img/5_background/layers/air.png', 0 , 719*2),
    new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 180 , 719*2),
    new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 180 , 719*2),
    new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 180 , 719*2),

    new BackgroundObject('img/5_background/layers/air.png', 0 , 719*3),
    new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 180 , 719*3),
    new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 180 , 719*3),
    new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 180 , 719*3),
],
[
    new Coin(),
    new Coin(),
    new Coin(),
    new Coin(),
    new Coin(),
    new Coin(),
    new Coin(),
    new Coin(),
    new Coin(),
    new Coin(),
],
[
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
]
,);